### Primeiros passos no uso da biblioteca NumPy

In [1]:
#Importando o pacote
import numpy as np
#Versão do pacote
print(np.__version__)

1.20.1


In [2]:
### Exemplo I - Criando os primeiros arrays no NumPy
arr=np.array([1,2,3,4,5])
type(arr)

numpy.ndarray

In [3]:
#Exemplo II - Criando um array bidimensional
arr2=np.array([(1,4,5),(7,8,9)])
arr2

array([[1, 4, 5],
       [7, 8, 9]])

In [4]:
#Exemplo III - Criando uma matriz cheia de zeros, com dimensão especifica
arr = np.zeros((4,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
#Exemplo IV - Criando uma matriz cheia de uns, com dimensão especifica
arr=np.ones((4,7))
print(arr)
print(arr.shape) #Mostra a dimensão da matriz

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
(4, 7)


In [6]:
#Exemplo V - Criando uma matriz com uns na diagonal principal e zero no resto
arr=np.eye(8)
print(arr)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [7]:
#Gerando arrays com sequencias de dados (estilo range)
a=np.arange(0,10,0.9)
print(a)
b=np.arange(1,50,5)
print(b)

#Gerando arrays com n dados dentro de um intervalo específico
c=np.linspace(0,10,5) # 5 números entre 0 e 10, igualmente espaçados
print(c)

[0.  0.9 1.8 2.7 3.6 4.5 5.4 6.3 7.2 8.1 9.  9.9]
[ 1  6 11 16 21 26 31 36 41 46]
[ 0.   2.5  5.   7.5 10. ]


In [8]:
#Ordenando arrays
a1=np.array([3,5,2,1,6,7,2,0,4,2])
print(np.sort(a1))

[0 1 2 2 2 3 4 5 6 7]


In [9]:
#Exemplo VI - Estatísticas a partir de um array(matriz)
matriz=np.array([(5,9,11),(-3,-4,7),(11,21,-10)])
print(matriz)
print(matriz.min())
print(matriz.max())
print(matriz.sum())
print(matriz.mean())
print(matriz.std())

[[  5   9  11]
 [ -3  -4   7]
 [ 11  21 -10]]
-10
21
47
5.222222222222222
8.929075823495307


In [10]:
#Operações entre matrizes e um escalar
print(matriz)
print(3*matriz)
print(2+matriz)

[[  5   9  11]
 [ -3  -4   7]
 [ 11  21 -10]]
[[ 15  27  33]
 [ -9 -12  21]
 [ 33  63 -30]]
[[ 7 11 13]
 [-1 -2  9]
 [13 23 -8]]


In [12]:
#Gerando matrizes a partir de números aleatórios
#Eh necessario importar um modulo chamado random (do proprio numpy)
from numpy import random
np.random.seed(1234)
aleat=np.random.randint(1,100,10)
print(aleat)
print(aleat/10)

[48 84 39 54 77 25 16 50 24 27]
[4.8 8.4 3.9 5.4 7.7 2.5 1.6 5.  2.4 2.7]


In [13]:
#Operações entre arrays
a=np.random.randint(1,60,6)
print(a)
b=np.random.randint(1,50,6)
print(b)
print(a+b)

[31 44 31 45 27 55]
[49 29  6 17 10 48]
[ 80  73  37  62  37 103]


In [14]:
#Operações entre arrays - A falsa mutiplicacao de matrizes
a1=np.random.randint(1,60,[3,6])
print(a1)
a2=np.random.randint(1,60,[3,6])
print(a2)
print(a1*a2)

[[51 49 13 38 35 39]
 [59  4 40 12  1 42]
 [12 17  4  3 20 13]]
[[ 2 12 52 44 59 18]
 [15 52  8 43 44 47]
 [29 18 24 14 53 33]]
[[ 102  588  676 1672 2065  702]
 [ 885  208  320  516   44 1974]
 [ 348  306   96   42 1060  429]]


In [15]:
#A verdadeira multiplicação de matrizes
#numero de colunas da primeira matriz tem que ser igual ao numero de linhas da segunda matriz
a=np.random.randint(1,10,[3,2])
print(a)
b=np.random.randint(1,10,[2,3])
print(b)
#Multiplicacao das matrizes a e b (o resultado sera o nuimero de linhas de a vs o numero de colunas de b)
a.dot(b)

[[6 2]
 [6 5]
 [1 9]]
[[9 7 9]
 [7 4 2]]


array([[68, 50, 58],
       [89, 62, 64],
       [72, 43, 27]])

In [16]:
#Transposição de arrays
print(b)
print(b.shape) #Tamanho da matriz
print(b.T) #Transposição da matriz

[[9 7 9]
 [7 4 2]]
(2, 3)
[[9 7]
 [7 4]
 [9 2]]


In [17]:
#Determinante da matriz
A=np.random.randint(1,10,[4,4])
print(A)
#Determinante da matriz
print('O Determinante da matriz A é :', np.linalg.det(A)) #Muitas funções de álgebra linear estão no módulo linalg do NumPy
#Inversa da matriz A
print('A Inversa da matriz A é :', np.linalg.inv(A)) 

[[3 6 3 6]
 [7 8 5 4]
 [6 7 5 7]
 [3 5 3 8]]
O Determinante da matriz A é : -23.999999999999982
A Inversa da matriz A é : [[-1.29166667  1.125      -1.25        1.5       ]
 [ 0.41666667  0.25       -0.5         0.        ]
 [ 1.375      -1.875       2.75       -2.5       ]
 [-0.29166667  0.125      -0.25        0.5       ]]


In [18]:
#Comparação entre arrays (elemento a elemento)
a=np.array([1,4,7,10])
b=np.array([2,1,5,11])
print(a==b)
print(a!=b)
print(a>b)
print(a<b)

#Comparação entre arrays (array inteiro)
print(np.array_equal(a,b))
c=np.array([5,3])
d=np.array([5,3])
print(np.array_equal(c,d))

[False False False False]
[ True  True  True  True]
[False  True  True False]
[ True False False  True]
False
True


In [19]:
#Algumas funções matemáticas presentes
print(np.sum(a)) #Soma dos elementos do array
print(np.mean(a)) #Média dos elementos do array
print(np.std(a)) #Desvio padrão dos elementos do array

22
5.5
3.3541019662496847


In [20]:
a=np.array([(3,4, 5),(5, 6, 4),(5, 3, 2)])
a.shape

(3, 3)