## Realize as seguintes atividades usando um notebook Jupyter

a) Explore um pouco o módulo “math”. Que funções ou constantes podem ser interessantes?

b) Crie um array com a seguinte característica: "[[3 4 5] [5 6 4] [5 3 2]]". Calcule a dimensão dessa matriz. Qual o
determinante e a inversa dessa matriz? Extraia estatísticas descritivas dessa matriz (mínimo, média, máximo e
desvio padrão).

c) Gere 2 matrizes com numeros inteiros aleatórios e promova a multiplicação entre elas. Houve algum erro? Qual
a condição para que seja possível a multiplicação de 2 matrizes? Qual deve ser o formato da matriz resultante?

d) Gere um array que seja uma sequência de números de 0 a 10, com razão de 1.2.

e) Gere um array que seja uma sequência de números de 100 a 10, com razão de -15.

f) Gere uma matriz de 6x6, sendo cada linha uma sugestão aleatória de dezenas para um jogo da megasena.

In [1]:
import math
import numpy as np
import pandas as pd

In [2]:
import numpy as np

arr=np.array([(3,4,5),(5,6,4),(5,3,2)])
arr

array([[3, 4, 5],
       [5, 6, 4],
       [5, 3, 2]])

In [3]:
arr.shape

(3, 3)

In [2]:
print(math.factorial(8))   # n!
print(math.comb(60, 6))    # n! / (k! * (n - k)!)
print(math.perm(60, 6))    # n! / (n - k)!

40320
50063860
36045979200


In [3]:
print(math.e)
print(math.tau)   # Tau is a circle constant equal to 2π

2.718281828459045
6.283185307179586


In [4]:
angle = [-math.pi, -math.pi / 2, 0, math.pi / 2, math.pi] 

sin = [math.sin(a) for a in angle]
cos = [math.cos(a) for a in angle]
tan = [math.tan(a) for a in angle]

pd.DataFrame({'angle': angle, 'sin': sin, 'cos': cos, 'tan': tan})

angle           sin           cos           tan
0 -3.141593 -1.224647e-16 -1.000000e+00  1.224647e-16
1 -1.570796 -1.000000e+00  6.123234e-17 -1.633124e+16
2  0.000000  0.000000e+00  1.000000e+00  0.000000e+00
3  1.570796  1.000000e+00  6.123234e-17  1.633124e+16
4  3.141593  1.224647e-16 -1.000000e+00 -1.224647e-16

In [5]:
matrix = np.array([[3, 4, 5], [5, 6, 4], [5, 3, 2]])

print("Dimensions: ", matrix.shape)
print("Determinant: ", round(np.linalg.det(matrix), 2))
print("Inverse: ", np.linalg.inv(matrix))
print("Minimum: ", np.min(matrix))
print("Mean: ", round(np.mean(matrix), 2))
print("Maximum: ", np.max(matrix))
print("Standard deviation: ", round(np.std(matrix), 2))

Dimensions:  (3, 3)
Determinant:  -35.0
Inverse:  [[ 0.         -0.2         0.4       ]
 [-0.28571429  0.54285714 -0.37142857]
 [ 0.42857143 -0.31428571  0.05714286]]
Minimum:  2
Mean:  4.11
Maximum:  6
Standard deviation:  1.2


In [6]:
np.random.seed(2022)

d1 = np.random.randint(3, 12)
d2 = np.random.randint(4, 13)
d3 = np.random.randint(5, 14)

A = np.random.randint(1, 100, (d1, d2))
B = np.random.randint(1, 100, (d2, d3))
C = A.dot(B)

print("A dimensions: {}\n{}".format(A.shape, A))
print("\nB dimensions: {}\n{}".format(B.shape, B))
print("\nA . B dimensions: {}\n{}".format(C.shape, C))

A dimensions: (3, 5)
[[56 89 19 25 17]
 [54 42 34 28 12]
 [20 95 76 49 20]]

B dimensions: (5, 6)
[[39 73 15 94 17 91]
 [12 95 98  3 81 16]
 [24 82 88 86 38 57]
 [84 13 46 91 77 15]
 [97 14 78 53 43 54]]

A . B dimensions: (3, 6)
[[ 7457 14664 13710 10341 11539  8896]
 [ 6942 11252 10142 11310  8284  8592]
 [ 9800 17634 20112 14220 15556  9487]]


In [7]:
np.arange(0, 11, 1.2)

array([ 0. ,  1.2,  2.4,  3.6,  4.8,  6. ,  7.2,  8.4,  9.6, 10.8])

In [8]:
np.arange(100, 9, -15)

array([100,  85,  70,  55,  40,  25,  10])

In [9]:
rng = np.random.default_rng()
lotery = np.asarray([sorted(rng.choice(61, size=6, replace=False)) for i in range(6)])

print("Lotery ticket dimensions: {}\n{}".format(lotery.shape, lotery))

Lotery ticket dimensions: (6, 6)
[[ 7 11 15 24 49 53]
 [14 26 32 35 44 59]
 [13 20 25 30 37 40]
 [19 36 40 45 57 58]
 [ 5 10 12 20 22 58]
 [ 1  8 12 15 28 53]]
